trigger:
#  branches:
#    include: [ "*" ]
  tags:
    include: [ "*" ]

pool: D61

variables:
  COMPONENT: frontend

resources:
  repositories:
    - repository: templates
      type: github
      name: raghudevopsb61/jenkins
      endpoint: ado-d61

stages:
  - template: az-docker.yml@templates


