apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: NAMESPACE
  labels:
    app: frontend
    env: NAMESPACE
    appVersion: "APPVERSION"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      env: NAMESPACE
      appVersion: "APPVERSION"
  template:
    metadata:
      labels:
        app: frontend
        env: NAMESPACE
        appVersion: "APPVERSION"
    spec:
      containers:
      - name: nginx
        image: 633788536644.dkr.ecr.us-east-1.amazonaws.com/frontend:APPVERSION
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: NAMESPACE
  labels:
    app: frontend
    env: NAMESPACE
    appVersion: "APPVERSION"
spec:
  type: LoadBalancer
  selector:
    app: frontend
    env: NAMESPACE
    appVersion: "APPVERSION"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
